#############################################################################
# Makefile for building: OnlineMaps
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  OnlineMaps.pro
# Template: app
# Command: /home/daq/QT/5.10.1/gcc_64/bin/qmake -o Makefile OnlineMaps.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../QT/5.10.1/gcc_64/include -I../../QT/5.10.1/gcc_64/include/QtWidgets -I../../QT/5.10.1/gcc_64/include/QtGui -I../../QT/5.10.1/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I../../QT/5.10.1/gcc_64/mkspecs/linux-g++
QMAKE         = /home/daq/QT/5.10.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/daq/QT/5.10.1/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/daq/QT/5.10.1/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = OnlineMaps1.0.0
DISTDIR = /home/daq/MAPS/MAPS_WUYE/.tmp/OnlineMaps1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/daq/QT/5.10.1/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/daq/QT/5.10.1/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MainWindow.cpp \
		loadconfig.cpp \
		sendcmd.cpp \
		recvdata.cpp \
		analyse.cpp \
		qringbuffer.cpp moc_MainWindow.cpp \
		moc_loadconfig.cpp \
		moc_sendcmd.cpp \
		moc_recvdata.cpp \
		moc_analyse.cpp
OBJECTS       = main.o \
		MainWindow.o \
		loadconfig.o \
		sendcmd.o \
		recvdata.o \
		analyse.o \
		qringbuffer.o \
		moc_MainWindow.o \
		moc_loadconfig.o \
		moc_sendcmd.o \
		moc_recvdata.o \
		moc_analyse.o
DIST          = ../../QT/5.10.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../QT/5.10.1/gcc_64/mkspecs/common/unix.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/linux.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/sanitize.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/g++-base.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../QT/5.10.1/gcc_64/mkspecs/qconfig.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/qt_config.prf \
		../../QT/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../QT/5.10.1/gcc_64/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		../../QT/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/toolchain.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/default_pre.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/default_post.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/warn_on.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/qt.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/resources.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/moc.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/uic.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/file_copies.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/exceptions.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/yacc.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/lex.prf \
		OnlineMaps.pro MainWindow.h \
		loadconfig.h \
		sendcmd.h \
		recvdata.h \
		analyse.h \
		qringbuffer.h main.cpp \
		MainWindow.cpp \
		loadconfig.cpp \
		sendcmd.cpp \
		recvdata.cpp \
		analyse.cpp \
		qringbuffer.cpp
QMAKE_TARGET  = OnlineMaps
DESTDIR       = 
TARGET        = OnlineMaps


first: all
####### Build rules

$(TARGET): ui_MainWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OnlineMaps.pro ../../QT/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../QT/5.10.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../QT/5.10.1/gcc_64/mkspecs/common/unix.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/linux.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/sanitize.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/g++-base.conf \
		../../QT/5.10.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../QT/5.10.1/gcc_64/mkspecs/qconfig.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../QT/5.10.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/qt_config.prf \
		../../QT/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../QT/5.10.1/gcc_64/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		../../QT/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/toolchain.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/default_pre.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/default_post.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/warn_on.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/qt.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/resources.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/moc.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/uic.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/file_copies.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/exceptions.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/yacc.prf \
		../../QT/5.10.1/gcc_64/mkspecs/features/lex.prf \
		OnlineMaps.pro \
		../../QT/5.10.1/gcc_64/lib/libQt5Widgets.prl \
		../../QT/5.10.1/gcc_64/lib/libQt5Gui.prl \
		../../QT/5.10.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile OnlineMaps.pro -spec linux-g++
../../QT/5.10.1/gcc_64/mkspecs/features/spec_pre.prf:
../../QT/5.10.1/gcc_64/mkspecs/common/unix.conf:
../../QT/5.10.1/gcc_64/mkspecs/common/linux.conf:
../../QT/5.10.1/gcc_64/mkspecs/common/sanitize.conf:
../../QT/5.10.1/gcc_64/mkspecs/common/gcc-base.conf:
../../QT/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../QT/5.10.1/gcc_64/mkspecs/common/g++-base.conf:
../../QT/5.10.1/gcc_64/mkspecs/common/g++-unix.conf:
../../QT/5.10.1/gcc_64/mkspecs/qconfig.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../QT/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../QT/5.10.1/gcc_64/mkspecs/features/qt_functions.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/qt_config.prf:
../../QT/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../QT/5.10.1/gcc_64/mkspecs/features/spec_post.prf:
../.qmake.stash:
../../QT/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/toolchain.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/default_pre.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/resolve_config.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/default_post.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/warn_on.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/qt.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/resources.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/moc.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/unix/opengl.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/uic.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/unix/thread.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/qmake_use.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/file_copies.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/exceptions.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/yacc.prf:
../../QT/5.10.1/gcc_64/mkspecs/features/lex.prf:
OnlineMaps.pro:
../../QT/5.10.1/gcc_64/lib/libQt5Widgets.prl:
../../QT/5.10.1/gcc_64/lib/libQt5Gui.prl:
../../QT/5.10.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile OnlineMaps.pro -spec linux-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../QT/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents MainWindow.h loadconfig.h sendcmd.h recvdata.h analyse.h qringbuffer.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp MainWindow.cpp loadconfig.cpp sendcmd.cpp recvdata.cpp analyse.cpp qringbuffer.cpp $(DISTDIR)/
	$(COPY_FILE) --parents MainWindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../QT/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h ../../QT/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MainWindow.cpp moc_loadconfig.cpp moc_sendcmd.cpp moc_recvdata.cpp moc_analyse.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_loadconfig.cpp moc_sendcmd.cpp moc_recvdata.cpp moc_analyse.cpp
moc_MainWindow.cpp: ../../QT/5.10.1/gcc_64/include/QtWidgets/QMainWindow \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtgui-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmargins.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrect.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsize.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpoint.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpalette.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcolor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgb.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgba64.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qbrush.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvector.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qmatrix.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpolygon.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qregion.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdatastream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiodevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qline.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtransform.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpainterpath.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qimage.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixelformat.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qshareddata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhash.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfont.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontinfo.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcursor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qkeysequence.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvariant.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdebug.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtextstream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlocale.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qset.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurlquery.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfile.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfiledevice.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qvector2d.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qicon.h \
		loadconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QObject \
		sendcmd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QString \
		recvdata.h \
		qringbuffer.h \
		analyse.h \
		MainWindow.h \
		moc_predefs.h \
		../../QT/5.10.1/gcc_64/bin/moc
	/home/daq/QT/5.10.1/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/daq/QT/5.10.1/gcc_64/mkspecs/linux-g++ -I/home/daq/MAPS/MAPS_WUYE -I/home/daq/QT/5.10.1/gcc_64/include -I/home/daq/QT/5.10.1/gcc_64/include/QtWidgets -I/home/daq/QT/5.10.1/gcc_64/include/QtGui -I/home/daq/QT/5.10.1/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MainWindow.h -o moc_MainWindow.cpp

moc_loadconfig.cpp: ../../QT/5.10.1/gcc_64/include/QtCore/QObject \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		loadconfig.h \
		moc_predefs.h \
		../../QT/5.10.1/gcc_64/bin/moc
	/home/daq/QT/5.10.1/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/daq/QT/5.10.1/gcc_64/mkspecs/linux-g++ -I/home/daq/MAPS/MAPS_WUYE -I/home/daq/QT/5.10.1/gcc_64/include -I/home/daq/QT/5.10.1/gcc_64/include/QtWidgets -I/home/daq/QT/5.10.1/gcc_64/include/QtGui -I/home/daq/QT/5.10.1/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include loadconfig.h -o moc_loadconfig.cpp

moc_sendcmd.cpp: ../../QT/5.10.1/gcc_64/include/QtCore/QObject \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QString \
		sendcmd.h \
		moc_predefs.h \
		../../QT/5.10.1/gcc_64/bin/moc
	/home/daq/QT/5.10.1/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/daq/QT/5.10.1/gcc_64/mkspecs/linux-g++ -I/home/daq/MAPS/MAPS_WUYE -I/home/daq/QT/5.10.1/gcc_64/include -I/home/daq/QT/5.10.1/gcc_64/include/QtWidgets -I/home/daq/QT/5.10.1/gcc_64/include/QtGui -I/home/daq/QT/5.10.1/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include sendcmd.h -o moc_sendcmd.cpp

moc_recvdata.cpp: ../../QT/5.10.1/gcc_64/include/QtCore/QObject \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		qringbuffer.h \
		recvdata.h \
		moc_predefs.h \
		../../QT/5.10.1/gcc_64/bin/moc
	/home/daq/QT/5.10.1/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/daq/QT/5.10.1/gcc_64/mkspecs/linux-g++ -I/home/daq/MAPS/MAPS_WUYE -I/home/daq/QT/5.10.1/gcc_64/include -I/home/daq/QT/5.10.1/gcc_64/include/QtWidgets -I/home/daq/QT/5.10.1/gcc_64/include/QtGui -I/home/daq/QT/5.10.1/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include recvdata.h -o moc_recvdata.cpp

moc_analyse.cpp: ../../QT/5.10.1/gcc_64/include/QtCore/QObject \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		qringbuffer.h \
		analyse.h \
		moc_predefs.h \
		../../QT/5.10.1/gcc_64/bin/moc
	/home/daq/QT/5.10.1/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/daq/QT/5.10.1/gcc_64/mkspecs/linux-g++ -I/home/daq/MAPS/MAPS_WUYE -I/home/daq/QT/5.10.1/gcc_64/include -I/home/daq/QT/5.10.1/gcc_64/include/QtWidgets -I/home/daq/QT/5.10.1/gcc_64/include/QtGui -I/home/daq/QT/5.10.1/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include analyse.h -o moc_analyse.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_MainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainWindow.h
ui_MainWindow.h: MainWindow.ui \
		../../QT/5.10.1/gcc_64/bin/uic
	/home/daq/QT/5.10.1/gcc_64/bin/uic MainWindow.ui -o ui_MainWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp MainWindow.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/QMainWindow \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtgui-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmargins.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrect.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsize.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpoint.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpalette.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcolor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgb.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgba64.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qbrush.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvector.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qmatrix.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpolygon.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qregion.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdatastream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiodevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qline.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtransform.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpainterpath.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qimage.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixelformat.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qshareddata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhash.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfont.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontinfo.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcursor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qkeysequence.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvariant.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdebug.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtextstream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlocale.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qset.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurlquery.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfile.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfiledevice.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qvector2d.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qicon.h \
		loadconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QObject \
		sendcmd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QString \
		recvdata.h \
		qringbuffer.h \
		analyse.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/QApplication \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qapplication.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qeventloop.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qguiapplication.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/QMainWindow \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtgui-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmargins.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrect.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsize.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpoint.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpalette.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcolor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgb.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgba64.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qbrush.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvector.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qmatrix.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpolygon.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qregion.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdatastream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiodevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qline.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtransform.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpainterpath.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qimage.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixelformat.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qshareddata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhash.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfont.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontinfo.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcursor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qkeysequence.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvariant.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdebug.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtextstream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlocale.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qset.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurlquery.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfile.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfiledevice.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qvector2d.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qicon.h \
		loadconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QObject \
		sendcmd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QString \
		recvdata.h \
		qringbuffer.h \
		analyse.h \
		ui_MainWindow.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QTimer \
		../../QT/5.10.1/gcc_64/include/QtCore/qtimer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasictimer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdatetime.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QtGlobal \
		../../QT/5.10.1/gcc_64/include/QtWidgets/QMessageBox \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qmessagebox.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qdialog.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/QFileDialog \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qfiledialog.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdir.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfileinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

loadconfig.o: loadconfig.cpp loadconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QObject \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QString \
		MainWindow.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/QMainWindow \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtgui-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmargins.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrect.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsize.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpoint.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpalette.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcolor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgb.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgba64.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qbrush.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvector.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qmatrix.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpolygon.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qregion.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdatastream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiodevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qline.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtransform.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpainterpath.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qimage.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixelformat.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qshareddata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhash.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfont.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontinfo.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcursor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qkeysequence.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvariant.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdebug.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtextstream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlocale.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qset.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurlquery.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfile.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfiledevice.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qvector2d.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qicon.h \
		sendcmd.h \
		recvdata.h \
		qringbuffer.h \
		analyse.h \
		ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loadconfig.o loadconfig.cpp

sendcmd.o: sendcmd.cpp MainWindow.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/QMainWindow \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtgui-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmargins.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrect.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsize.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpoint.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpalette.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcolor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgb.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgba64.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qbrush.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvector.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qmatrix.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpolygon.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qregion.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdatastream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiodevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qline.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtransform.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpainterpath.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qimage.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixelformat.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qshareddata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhash.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfont.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontinfo.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcursor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qkeysequence.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvariant.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdebug.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtextstream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlocale.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qset.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurlquery.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfile.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfiledevice.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qvector2d.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qicon.h \
		loadconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QObject \
		sendcmd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QString \
		recvdata.h \
		qringbuffer.h \
		analyse.h \
		ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sendcmd.o sendcmd.cpp

recvdata.o: recvdata.cpp recvdata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QObject \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		qringbuffer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QString \
		MainWindow.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/QMainWindow \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtgui-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmargins.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrect.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsize.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpoint.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpalette.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcolor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgb.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qrgba64.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qbrush.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvector.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qmatrix.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpolygon.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qregion.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdatastream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiodevice.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qline.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtransform.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpainterpath.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qimage.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixelformat.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qpixmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qshareddata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhash.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfont.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qfontinfo.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qcursor.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qkeysequence.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvariant.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qdebug.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtextstream.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlocale.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qset.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qurlquery.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfile.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qfiledevice.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qvector2d.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../QT/5.10.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../QT/5.10.1/gcc_64/include/QtGui/qicon.h \
		loadconfig.h \
		sendcmd.h \
		analyse.h \
		ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recvdata.o recvdata.cpp

analyse.o: analyse.cpp analyse.h \
		../../QT/5.10.1/gcc_64/include/QtCore/QObject \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../QT/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		qringbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analyse.o analyse.cpp

qringbuffer.o: qringbuffer.cpp qringbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qringbuffer.o qringbuffer.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_loadconfig.o: moc_loadconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loadconfig.o moc_loadconfig.cpp

moc_sendcmd.o: moc_sendcmd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sendcmd.o moc_sendcmd.cpp

moc_recvdata.o: moc_recvdata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_recvdata.o moc_recvdata.cpp

moc_analyse.o: moc_analyse.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_analyse.o moc_analyse.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

